export interface ProPlaylistTask {
    modeId: string;
    name: string;
    duration: number; // in seconds
    difficulty: "Eco" | "Bonus" | "Force Buy" | "Full Buy";
}

export interface ProPlaylist {
    id: string;
    proName: string;
    creatorType: "pro-team" | "specialist";
    gameFocus: "Valorant" | "CS2" | "Hybrid";
    team: string; // e.g., 'Sentinels', 'Team Spirit', 'Movement', 'Aim Community'
    description: string;
    accentColor: string; // Tailwind classes for text/border/glow states
    sequence: ProPlaylistTask[];
}

export const proPlaylists: ProPlaylist[] = [
    {
        id: "zekken",
        proName: "zekken",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "Sentinels",
        description: "High-tempo entry-duelist routine. Calibrates rapid micro-flicks, vertical-horizontal target sweeps, and jiggle peek reaction speeds.",
        accentColor: "border-red-500/30 hover:border-red-500 focus-within:border-red-500 shadow-red-500/5 hover:shadow-red-500/20",
        sequence: [
            {
                modeId: "static-flick",
                name: "1w6t Extra (Static Flick)",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "jiggle-peek",
                name: "Jiggle Peek Duel",
                duration: 60,
                difficulty: "Force Buy",
            },
            {
                modeId: "burst-reaction",
                name: "Reflex Cluster Snap",
                duration: 60,
                difficulty: "Full Buy",
            },
        ],
    },
    {
        id: "forsaken",
        proName: "f0rsakeN",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "Paper Rex",
        description: "Ultra-versatile agent flex routine. Features target-switching click timing, continuous high-velocity tracking, and sound localization snap drills.",
        accentColor: "border-pink-500/30 hover:border-pink-500 focus-within:border-pink-500 shadow-pink-500/5 hover:shadow-pink-500/20",
        sequence: [
            {
                modeId: "flick-track-hybrid",
                name: "Pasu Click Voltaic",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "continuous-track",
                name: "Air Tracking Voltaic",
                duration: 60,
                difficulty: "Force Buy",
            },
            {
                modeId: "blind-flick",
                name: "Sound Spatialization Anchor",
                duration: 60,
                difficulty: "Bonus",
            },
        ],
    },
    {
        id: "jinggg",
        proName: "Jinggg",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "Paper Rex",
        description: "Explosive entry movement routine. Designed to calibrate smooth crosshair placement and tracking during maximum speed Raze/Neon flight maneuvers.",
        accentColor: "border-purple-500/30 hover:border-purple-500 focus-within:border-purple-500 shadow-purple-500/5 hover:shadow-purple-500/20",
        sequence: [
            {
                modeId: "tracking-while-moving",
                name: "Apex Dynamic Tracking",
                duration: 60,
                difficulty: "Bonus",
            },
            {
                modeId: "static-flick",
                name: "Speed Flicking 180",
                duration: 45,
                difficulty: "Full Buy",
            },
            {
                modeId: "micro-precision",
                name: "Wrist Micro Precision",
                duration: 60,
                difficulty: "Full Buy",
            },
        ],
    },
    {
        id: "something",
        proName: "something",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "Paper Rex",
        description: "PRX sniper & entry demon routine. Focuses on maximum velocity micro-flicks, reflex snapping, and wide-angle target switching.",
        accentColor: "border-indigo-500/30 hover:border-indigo-500 focus-within:border-indigo-500 shadow-indigo-500/5 hover:shadow-indigo-500/20",
        sequence: [
            {
                modeId: "reaction-test",
                name: "AWP Reflex Microflick",
                duration: 45,
                difficulty: "Full Buy",
            },
            {
                modeId: "spatial-flick",
                name: "Wide Angle Snap 180",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "flick-track-hybrid",
                name: "Decoy Target Switch",
                duration: 60,
                difficulty: "Full Buy",
            },
        ],
    },
    {
        id: "tenz",
        proName: "TenZ",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "Sentinels",
        description: "High-intensity micro-flicking and maximum mechanical velocity tracking, replicating TenZ's signature high-sens snapping style.",
        accentColor: "border-red-500/30 hover:border-red-500 focus-within:border-red-500 shadow-red-500/5 hover:shadow-red-500/20",
        sequence: [
            {
                modeId: "static-flick",
                name: "1w6t Extra (Static Flick)",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "micro-precision",
                name: "Micro Shot Speed",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "continuous-track",
                name: "Smooth Thin Strafes",
                duration: 60,
                difficulty: "Force Buy",
            },
        ],
    },
    {
        id: "aspas",
        proName: "aspas",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "Leviatán",
        description: "Flawless crosshair tracking and perfectly paced lateral angle sweeping, simulating his smooth and consistent target tracking.",
        accentColor: "border-cyan-500/30 hover:border-cyan-500 focus-within:border-cyan-500 shadow-cyan-500/5 hover:shadow-cyan-500/20",
        sequence: [
            {
                modeId: "continuous-track",
                name: "Air Tracking Voltaic",
                duration: 60,
                difficulty: "Force Buy",
            },
            {
                modeId: "flick-track-hybrid",
                name: "Pasu Click Voltaic",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "jiggle-peek",
                name: "Jiggle Peek Angle Hold",
                duration: 60,
                difficulty: "Force Buy",
            },
        ],
    },
    {
        id: "yay",
        proName: "yay",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "Optic / Bleed",
        description: "The 'El Diablo' robotic calibration routine. Features low-sens pixel-perfect static micro-adjustments and steady angle-peeking.",
        accentColor: "border-green-500/30 hover:border-green-500 focus-within:border-green-500 shadow-green-500/5 hover:shadow-green-500/20",
        sequence: [
            {
                modeId: "micro-precision",
                name: "Robotic Microflick",
                duration: 90,
                difficulty: "Full Buy",
            },
            {
                modeId: "static-flick",
                name: "1w4ts Static Click",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "jiggle-peek",
                name: "Robotic Peek Duel",
                duration: 60,
                difficulty: "Bonus",
            },
        ],
    },
    {
        id: "primmie",
        proName: "Primmie",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "Talon Esports",
        description: "Aggressive ranked-demon style high-sensitivity snapping and quick reaction targets to warm up raw entry flicking velocity.",
        accentColor: "border-amber-500/30 hover:border-amber-500 focus-within:border-amber-500 shadow-amber-500/5 hover:shadow-amber-500/20",
        sequence: [
            {
                modeId: "static-flick",
                name: "Speed Flicking 180",
                duration: 45,
                difficulty: "Full Buy",
            },
            {
                modeId: "cognitive-overdrive",
                name: "Cognitive Overdrive Snap",
                duration: 60,
                difficulty: "Force Buy",
            },
            {
                modeId: "burst-reaction",
                name: "Target Switch Burst",
                duration: 60,
                difficulty: "Full Buy",
            },
        ],
    },
    {
        id: "donk",
        proName: "donk",
        creatorType: "pro-team",
        gameFocus: "CS2",
        team: "Team Spirit",
        description: "Pure explosive spray tracking and aggressive crosshair pulling mechanics, built for CS2 entry duelists.",
        accentColor: "border-teal-500/30 hover:border-teal-500 focus-within:border-teal-500 shadow-teal-500/5 hover:shadow-teal-500/20",
        sequence: [
            {
                modeId: "recoil-reactive",
                name: "CS2 Spray Control",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "flick-track-hybrid",
                name: "Horizontal Flick Sweeping",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "cognitive-overdrive",
                name: "Decoy Target Discrimination",
                duration: 60,
                difficulty: "Force Buy",
            },
        ],
    },
    {
        id: "m0nesy",
        proName: "m0NESY",
        creatorType: "pro-team",
        gameFocus: "CS2",
        team: "G2 Esports",
        description: "AWP reflex snapping at wide angles, featuring insane mechanical reaction speeds and micro-precision resets.",
        accentColor: "border-slate-400/30 hover:border-slate-400 focus-within:border-slate-400 shadow-slate-400/5 hover:shadow-slate-400/20",
        sequence: [
            {
                modeId: "reaction-test",
                name: "AWP Reflex Microflick",
                duration: 45,
                difficulty: "Full Buy",
            },
            {
                modeId: "spatial-flick",
                name: "Wide Angle Snap 180",
                duration: 60,
                difficulty: "Force Buy",
            },
            {
                modeId: "flick-track-hybrid",
                name: "Decoy Target Switch",
                duration: 60,
                difficulty: "Full Buy",
            },
        ],
    },
    {
        id: "ropz",
        proName: "ropz",
        creatorType: "pro-team",
        gameFocus: "CS2",
        team: "FaZe Clan",
        description: "Mathematical isolation and perfect static crosshair alignment, relying on zero hand tension and structured angles.",
        accentColor: "border-rose-500/30 hover:border-rose-500 focus-within:border-rose-500 shadow-rose-500/5 hover:shadow-rose-500/20",
        sequence: [
            {
                modeId: "recoil-reactive",
                name: "Recoil Pattern Memory",
                duration: 90,
                difficulty: "Full Buy",
            },
            {
                modeId: "micro-precision",
                name: "Angle Snap Isolation",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "continuous-track",
                name: "Methodical Thin Tracking",
                duration: 60,
                difficulty: "Eco",
            },
        ],
    },
    {
        id: "niko",
        proName: "NiKo",
        creatorType: "pro-team",
        gameFocus: "CS2",
        team: "G2 Esports",
        description: "Pure CS2 rifling standard. Clean horizontal snapping, deagle one-tap discipline, and vertical micro-adjustments.",
        accentColor: "border-sky-400/30 hover:border-sky-400 focus-within:border-sky-400 shadow-sky-400/5 hover:shadow-sky-400/20",
        sequence: [
            {
                modeId: "spatial-flick",
                name: "Deagle Horizontal Sweep",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "micro-precision",
                name: "Headshot Micro-Adjust",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "reaction-test",
                name: "Deagle Reflex Flash",
                duration: 45,
                difficulty: "Full Buy",
            },
        ],
    },
    {
        id: "scream",
        proName: "ScreaM",
        creatorType: "pro-team",
        gameFocus: "Hybrid",
        team: "Karmine Corp / Legend",
        description: "The legendary One-Tap routine. Focuses on minimal hand tension, flawless single-click precision, and pixel headshot calibration.",
        accentColor: "border-blue-400/30 hover:border-blue-400 focus-within:border-blue-400 shadow-blue-400/5 hover:shadow-blue-400/20",
        sequence: [
            {
                modeId: "micro-precision",
                name: "One-Tap Headshot Drill",
                duration: 90,
                difficulty: "Full Buy",
            },
            {
                modeId: "static-flick",
                name: "Static Snap Small",
                duration: 60,
                difficulty: "Full Buy",
            },
        ],
    },
    {
        id: "s1mple",
        proName: "s1mple",
        creatorType: "pro-team",
        gameFocus: "CS2",
        team: "Natus Vincere",
        description: "Highly aggressive, twitchy, and unpredictable micro-adjusting protocols designed for reactive multi-target snapping.",
        accentColor: "border-amber-400/30 hover:border-amber-400 focus-within:border-amber-400 shadow-amber-400/5 hover:shadow-amber-400/20",
        sequence: [
            {
                modeId: "spatial-flick",
                name: "Twitch Snapping 180",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "micro-precision",
                name: "Micro Target Adjustment",
                duration: 45,
                difficulty: "Full Buy",
            },
            {
                modeId: "recoil-reactive",
                name: "Spray Evasion Control",
                duration: 60,
                difficulty: "Full Buy",
            },
        ],
    },
    {
        id: "tarik",
        proName: "tarik",
        creatorType: "specialist",
        gameFocus: "Valorant",
        team: "Sentinels / Creator",
        description: "Tarik's ranked warmup protocol. Focuses on dynamic snapping, cognitive target switching, and building high-speed entry muscle memory.",
        accentColor: "border-red-400/30 hover:border-red-400 focus-within:border-red-400 shadow-red-400/5 hover:shadow-red-500/20",
        sequence: [
            {
                modeId: "flick-track-hybrid",
                name: "Tarik Target Switch",
                duration: 60,
                difficulty: "Force Buy",
            },
            {
                modeId: "static-flick",
                name: "Gridshot Speed Snap",
                duration: 60,
                difficulty: "Bonus",
            },
            {
                modeId: "burst-reaction",
                name: "Reflex Cluster Snap",
                duration: 60,
                difficulty: "Full Buy",
            },
        ],
    },
    {
        id: "iitztimmy",
        proName: "iiTzTimmy",
        creatorType: "specialist",
        gameFocus: "Hybrid",
        team: "100 Thieves",
        description: "Multi-genre tracking and movement alignment. Designed to build target focus during rapid sliding, jumping, and target transition.",
        accentColor: "border-rose-600/30 hover:border-rose-600 focus-within:border-rose-600 shadow-rose-600/5 hover:shadow-rose-600/20",
        sequence: [
            {
                modeId: "tracking-while-moving",
                name: "Apex Dynamic Tracking",
                duration: 60,
                difficulty: "Bonus",
            },
            {
                modeId: "flick-track-hybrid",
                name: "Fast Switch Clicking",
                duration: 60,
                difficulty: "Force Buy",
            },
            {
                modeId: "blind-flick",
                name: "Audio Spatialization Anchor",
                duration: 60,
                difficulty: "Full Buy",
            },
        ],
    },
    {
        id: "shroud",
        proName: "shroud",
        creatorType: "specialist",
        gameFocus: "Hybrid",
        team: "Legend",
        description: "Pure instinctual mouse-to-target muscle memory translation, featuring smooth vertical-to-horizontal snaps and tracking resets.",
        accentColor: "border-indigo-500/30 hover:border-indigo-500 focus-within:border-indigo-500 shadow-indigo-500/5 hover:shadow-indigo-500/20",
        sequence: [
            {
                modeId: "static-flick",
                name: "Instinctual Snapping",
                duration: 60,
                difficulty: "Bonus",
            },
            {
                modeId: "continuous-track",
                name: "Smooth Bot Tracking",
                duration: 60,
                difficulty: "Force Buy",
            },
            {
                modeId: "flick-track-hybrid",
                name: "Target Switch Control",
                duration: 60,
                difficulty: "Full Buy",
            },
        ],
    },
    {
        id: "kaemi",
        proName: "Kaemi",
        creatorType: "specialist",
        gameFocus: "Valorant",
        team: "Aim Community",
        description: "The 'Marshal God' sequence. High verticality, fast scope reaction, and target snap confirmation.",
        accentColor: "border-yellow-500/30 hover:border-yellow-500 focus-within:border-yellow-500 shadow-yellow-500/5 hover:shadow-yellow-500/20",
        sequence: [
            {
                modeId: "vertical-flick",
                name: "Vertical Flick Calibrator",
                duration: 60,
                difficulty: "Force Buy",
            },
            {
                modeId: "static-flick",
                name: "Static Headshot Snap",
                duration: 60,
                difficulty: "Full Buy",
            },
        ],
    },
    {
        id: "temet",
        proName: "Temet",
        creatorType: "specialist",
        gameFocus: "Valorant",
        team: "Movement",
        description: "Neon velocity simulation. Tracks target velocity smoothly while moving at maximum speed.",
        accentColor: "border-pink-500/30 hover:border-pink-500 focus-within:border-pink-500 shadow-pink-500/5 hover:shadow-pink-500/20",
        sequence: [
            {
                modeId: "tracking-while-moving",
                name: "Tracking while Moving",
                duration: 60,
                difficulty: "Bonus",
            },
            {
                modeId: "spatial-flick",
                name: "Spatial Flick Snap",
                duration: 45,
                difficulty: "Full Buy",
            },
        ],
    },
    {
        id: "horcus",
        proName: "Horcus",
        creatorType: "specialist",
        gameFocus: "Valorant",
        team: "Aim Community",
        description: "Extreme wrist speed-flicking and rapid target transfer. Designed for fast reaction twitchers.",
        accentColor: "border-purple-500/30 hover:border-purple-500 focus-within:border-purple-500 shadow-purple-500/5 hover:shadow-purple-500/20",
        sequence: [
            {
                modeId: "smoothness-track",
                name: "Smoothness Tracking",
                duration: 90,
                difficulty: "Eco",
            },
            {
                modeId: "micro-precision",
                name: "Wrist Micro Precision",
                duration: 60,
                difficulty: "Bonus",
            },
        ],
    },
    {
        id: "rawzu",
        proName: "Rawzu",
        creatorType: "specialist",
        gameFocus: "Valorant",
        team: "Aim Community",
        description: "The 'Calm Aim' blueprint—complete eradication of hand tension and panic target snapping.",
        accentColor: "border-emerald-500/30 hover:border-emerald-500 focus-within:border-emerald-500 shadow-emerald-500/5 hover:shadow-emerald-500/20",
        sequence: [
            {
                modeId: "static-flick",
                name: "Calm Static Flick",
                duration: 120,
                difficulty: "Eco",
            },
            {
                modeId: "micro-precision",
                name: "Tension Free Micro-Adjust",
                duration: 60,
                difficulty: "Eco",
            },
        ],
    },
    {
        id: "alfajer",
        proName: "Alfajer",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "Fnatic",
        description: "Methodical site anchor warmup. High micro-adjust accuracy, spray control, and calm crosshair sweeps.",
        accentColor: "border-orange-500/30 hover:border-orange-500 focus-within:border-orange-500 shadow-orange-500/5 hover:shadow-orange-500/20",
        sequence: [
            {
                modeId: "micro-precision",
                name: "Micro Shot Precision",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "static-flick",
                name: "1w6t Extra (Static Flick)",
                duration: 60,
                difficulty: "Bonus",
            },
        ],
    },
    {
        id: "kangkang",
        proName: "KangKang",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "EDward Gaming",
        description: "CN sniper and Jett legend routine. Hyper-aggressive reaction flicks and wide spatial target transitions.",
        accentColor: "border-red-600/30 hover:border-red-600 focus-within:border-red-600 shadow-red-600/5 hover:shadow-red-600/20",
        sequence: [
            {
                modeId: "reaction-test",
                name: "AWP Reflex Flash",
                duration: 45,
                difficulty: "Full Buy",
            },
            {
                modeId: "spatial-flick",
                name: "Wide Angle Snap 180",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "jiggle-peek",
                name: "Jiggle Peek Duel",
                duration: 60,
                difficulty: "Force Buy",
            },
        ],
    },
    {
        id: "d4v41",
        proName: "d4v41",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "Paper Rex",
        description: "The structural anchor of PRX. Balanced micro-corrections, passive angle tracking, and target switching clicking.",
        accentColor: "border-pink-500/30 hover:border-pink-500 focus-within:border-pink-500 shadow-pink-500/5 hover:shadow-pink-500/20",
        sequence: [
            {
                modeId: "flick-track-hybrid",
                name: "Pasu Click Voltaic",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "continuous-track",
                name: "Smooth Thin Strafes",
                duration: 60,
                difficulty: "Force Buy",
            },
        ],
    },
    {
        id: "chronicle",
        proName: "Chronicle",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "Team Vitality",
        description: "Multi-trophy champion flex warmup. Focuses on flat horizontal sweeps, recoil evasion tracking, and entry snap efficiency.",
        accentColor: "border-yellow-400/30 hover:border-yellow-400 focus-within:border-yellow-400 shadow-yellow-400/5 hover:shadow-yellow-400/20",
        sequence: [
            {
                modeId: "spatial-flick",
                name: "Horizontal Sweep",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "recoil-reactive",
                name: "CS2 Spray Control",
                duration: 60,
                difficulty: "Force Buy",
            },
        ],
    },
    {
        id: "bang",
        proName: "bang",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "100 Thieves",
        description: "Robotic controller site anchor routine. Focuses on horizontal target switching and static headshot snaps.",
        accentColor: "border-red-600/30 hover:border-red-600 focus-within:border-red-600 shadow-red-600/5 hover:shadow-red-600/20",
        sequence: [
            {
                modeId: "flick-track-hybrid",
                name: "Decoy Target Switch",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "static-flick",
                name: "1w4ts Static Click",
                duration: 60,
                difficulty: "Full Buy",
            },
        ],
    },
    {
        id: "oxy",
        proName: "OXY",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "Cloud9",
        description: "High-sensitivity flick demon routine. Replicates OXY's explosive duelist snaps and target switching click timings.",
        accentColor: "border-blue-400/30 hover:border-blue-400 focus-within:border-blue-400 shadow-blue-400/5 hover:shadow-blue-400/20",
        sequence: [
            {
                modeId: "static-flick",
                name: "Speed Flicking 180",
                duration: 45,
                difficulty: "Full Buy",
            },
            {
                modeId: "flick-track-hybrid",
                name: "Pasu Click Voltaic",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "burst-reaction",
                name: "Reflex Cluster Snap",
                duration: 60,
                difficulty: "Full Buy",
            },
        ],
    },
    {
        id: "dambi",
        proName: "Dambi",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "NS RedForce",
        description: "Korean Challengers site entry routine. Precision micro-snaps and clean angle clearing sweep runs.",
        accentColor: "border-red-500/30 hover:border-red-500 focus-within:border-red-500 shadow-red-500/5 hover:shadow-red-500/20",
        sequence: [
            {
                modeId: "micro-precision",
                name: "Robotic Microflick",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "spatial-flick",
                name: "Wide Angle Snap 180",
                duration: 60,
                difficulty: "Bonus",
            },
        ],
    },
    {
        id: "boo",
        proName: "Boo",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "Team Heretics",
        description: "IGL dynamic support routine. Calm tracking, auditory snap checks, and site entry target switching.",
        accentColor: "border-orange-400/30 hover:border-orange-400 focus-within:border-orange-400 shadow-orange-400/5 hover:shadow-orange-400/20",
        sequence: [
            {
                modeId: "continuous-track",
                name: "Smooth Thin Strafes",
                duration: 60,
                difficulty: "Force Buy",
            },
            {
                modeId: "blind-flick",
                name: "Audio Spatialization Anchor",
                duration: 60,
                difficulty: "Bonus",
            },
        ],
    },
    {
        id: "leaf",
        proName: "leaf",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "G2 Esports",
        description: "Ultra-consistent flex duelist/sentinel warmup. High time-on-target tracking and horizontal micro-flicks.",
        accentColor: "border-slate-300/30 hover:border-slate-300 focus-within:border-slate-300 shadow-slate-300/5 hover:shadow-slate-300/20",
        sequence: [
            {
                modeId: "continuous-track",
                name: "Smooth Bot Tracking",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "micro-precision",
                name: "Headshot Micro-Adjust",
                duration: 60,
                difficulty: "Full Buy",
            },
        ],
    },
    {
        id: "derke",
        proName: "Derke",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "Team Vitality",
        description: "Derke's entry-duelist warmup protocol. Designed for rapid duelist target switching and clean target snapping under pressure.",
        accentColor: "border-yellow-400/30 hover:border-yellow-400 focus-within:border-yellow-400 shadow-yellow-400/5 hover:shadow-yellow-400/20",
        sequence: [
            {
                modeId: "flick-track-hybrid",
                name: "Decoy Target Switch",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "static-flick",
                name: "1w6t Extra (Static Flick)",
                duration: 60,
                difficulty: "Bonus",
            },
        ],
    },
    {
        id: "asuna",
        proName: "Asuna",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "100 Thieves",
        description: "High-sens jitter-aim and spray transfer routine. Emulates Asuna's signature rapid target-shaking and snap tracking.",
        accentColor: "border-red-600/30 hover:border-red-600 focus-within:border-red-600 shadow-red-600/5 hover:shadow-red-600/20",
        sequence: [
            {
                modeId: "recoil-reactive",
                name: "CS2 Spray Control",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "flick-track-hybrid",
                name: "Tarik Target Switch",
                duration: 60,
                difficulty: "Force Buy",
            },
            {
                modeId: "static-flick",
                name: "Gridshot Speed Snap",
                duration: 60,
                difficulty: "Bonus",
            },
        ],
    },
    {
        id: "crashies",
        proName: "crashies",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "Fnatic",
        description: "Initiator static angle hold and micro-flick isolation routine. Replicates crashies' steady and clinical aim style.",
        accentColor: "border-orange-500/30 hover:border-orange-500 focus-within:border-orange-500 shadow-orange-500/5 hover:shadow-orange-500/20",
        sequence: [
            {
                modeId: "micro-precision",
                name: "Robotic Microflick",
                duration: 90,
                difficulty: "Full Buy",
            },
            {
                modeId: "jiggle-peek",
                name: "Jiggle Peek Angle Hold",
                duration: 60,
                difficulty: "Full Buy",
            },
        ],
    },
    {
        id: "s0m",
        proName: "s0m",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "NRG",
        description: "The W0mpeee ranked-prep warmup. High velocity tracking, static flick click timings, and target switching.",
        accentColor: "border-blue-500/30 hover:border-blue-500 focus-within:border-blue-500 shadow-blue-500/5 hover:shadow-blue-500/20",
        sequence: [
            {
                modeId: "continuous-track",
                name: "Smooth Thin Strafes",
                duration: 60,
                difficulty: "Force Buy",
            },
            {
                modeId: "static-flick",
                name: "1w6t Extra (Static Flick)",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "flick-track-hybrid",
                name: "Decoy Target Switch",
                duration: 60,
                difficulty: "Full Buy",
            },
        ],
    },
    {
        id: "ethan",
        proName: "Ethan",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "NRG",
        description: "Support champion crosshair placement routine. Focuses on flat horizontal sweeps, micro-adjustments, and low hand tension.",
        accentColor: "border-indigo-500/30 hover:border-indigo-500 focus-within:border-indigo-500 shadow-indigo-500/5 hover:shadow-indigo-500/20",
        sequence: [
            {
                modeId: "spatial-flick",
                name: "Deagle Horizontal Sweep",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "micro-precision",
                name: "Tension Free Micro-Adjust",
                duration: 60,
                difficulty: "Eco",
            },
        ],
    },
    {
        id: "jawgemo",
        proName: "jawgemo",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "G2 Esports",
        description: "Explosive Jett/Raze entry-fragger routine. Focuses on dynamic movement tracking and speed flicks.",
        accentColor: "border-slate-300/30 hover:border-slate-300 focus-within:border-slate-300 shadow-slate-300/5 hover:shadow-slate-300/20",
        sequence: [
            {
                modeId: "tracking-while-moving",
                name: "Apex Dynamic Tracking",
                duration: 60,
                difficulty: "Bonus",
            },
            {
                modeId: "static-flick",
                name: "Speed Flicking 180",
                duration: 45,
                difficulty: "Full Buy",
            },
        ],
    },
    {
        id: "jonahp",
        proName: "JonahP",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "G2 Esports",
        description: "The 'Professor' flex routine. Extremely versatile set of tracking, jiggle-peek, and static micro-adjustments.",
        accentColor: "border-sky-500/30 hover:border-sky-500 focus-within:border-sky-500 shadow-sky-500/5 hover:shadow-sky-500/20",
        sequence: [
            {
                modeId: "continuous-track",
                name: "Smooth Bot Tracking",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "jiggle-peek",
                name: "Jiggle Peek Angle Hold",
                duration: 60,
                difficulty: "Force Buy",
            },
            {
                modeId: "micro-precision",
                name: "Headshot Micro-Adjust",
                duration: 60,
                difficulty: "Full Buy",
            },
        ],
    },
    {
        id: "johnqt",
        proName: "johnqt",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "Sentinels",
        description: "Sentinels IGL strategic warmup. Precision horizontal checking, recoil patterns, and support site defense snaps.",
        accentColor: "border-red-500/30 hover:border-red-500 focus-within:border-red-500 shadow-red-500/5 hover:shadow-red-500/20",
        sequence: [
            {
                modeId: "spatial-flick",
                name: "Deagle Horizontal Sweep",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "micro-precision",
                name: "Robotic Microflick",
                duration: 60,
                difficulty: "Full Buy",
            },
        ],
    },
    {
        id: "zellsis",
        proName: "Zellsis",
        creatorType: "pro-team",
        gameFocus: "Valorant",
        team: "Sentinels",
        description: "High energy vibe-captain warmup. Replicates Zellsis' entry duelist snap angles, target switching click timings, and spray control.",
        accentColor: "border-red-500/30 hover:border-red-500 focus-within:border-red-500 shadow-red-500/5 hover:shadow-red-500/20",
        sequence: [
            {
                modeId: "flick-track-hybrid",
                name: "Tarik Target Switch",
                duration: 60,
                difficulty: "Force Buy",
            },
            {
                modeId: "recoil-reactive",
                name: "CS2 Spray Control",
                duration: 60,
                difficulty: "Full Buy",
            },
            {
                modeId: "static-flick",
                name: "1w6t Extra (Static Flick)",
                duration: 60,
                difficulty: "Bonus",
            },
        ],
    },
];
